### ISSUE TITLE
Add sections in pkgdown reference index

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/epidemics#107]
It would be useful to add sections and subsections in the pkgdown reference index to group function logically and help users understand the package structure.

Documentation: https://pkgdown.r-lib.org/reference/build_reference.html#reference-index

Some other examples in Epiverse-TRACE:

- https://epiverse-trace.github.io/linelist/reference/index.html
- https://epiverse-trace.github.io/epiparameter/reference/index.html

**Comment by pratikunterwegs** [comment]
Thanks, agreed, I'll tag this for potential work on the development day.
