### ISSUE TITLE
R0 vs Reff in vignettes

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epidemics#116]
In some of the vignettes, the epidemic starts off with more than one infected individual in a completely susceptible population, so I think the preferred terminology for the reproduction number should be Reff instead of R0.

**Comment by pratikunterwegs** [comment]
Thanks @jamesmbaazam - you're very welcome to make these edits.

**Comment by jamesmbaazam** [comment]
May be worth a broader discussion with @rozeggo and others. It might also require renaming the R0 arguments to something like "R" to keep it generic and open to the users' interpretation.

**Comment by pratikunterwegs** [comment]
The `r0` is a property of the `<infection>`, and is independent of the number of initial infections as @adamkucharski says, so it more properly refers to $R_0$. Happy to hear more thoughts on this, but it seems like the current usage is the correct one.

**Comment by pratikunterwegs** [comment]
Closing this following the above discussion.
