### ISSUE TITLE
Threshold for validating a population object.

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/epidemics#118]
Small numerical residue  in sum of population = 1.000001, raises validation error. "`initial_conditions` rows must always sum to 1.0". In the code you have set the threshold for validation to 1e-6, but this can be reduce, e.g., to 1e-3.

**Comment by pratikunterwegs** [comment]
Thanks @Degoot-AM - happy for you to make a PR and make this change.

**Comment by pratikunterwegs** [comment]
Hi @Degoot-AM - just checking whether you would be taking this up or should I move ahead with working on a fix?

**Comment by Degoot-AM** [comment]
Hi @pratikunterwegs , Welcome back. This is a small issue, I don't think it worth a PR. So fell free to fix it, by reducing the threshold. Thank you
