### ISSUE TITLE
`intervention()` function returns an extra element that comes as an empty string `""`

### ISSUE THREAD

**Issue by Karim-Mane** [epiverse-trace/epidemics#122]
*Bugs* may include behaviour that does not impact package functionality, but which seems as though it might not be intended by the package developers.
  
Please place an "x" in all the boxes that apply
---------------------------------------------
  
- [ x] I have the most recent version of epidemics and R
- [ x] I have found a bug
- [ x] I have a [reproducible example](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
- [ ] I want to request a new feature

--------
  
Please include a brief description of the problem with a code example:
In **test-interventions.R**, the object returned by the `intervention()` constructor is composed of 5 elements instead of 4. The extra element is an empty string (`""`). 
This makes the test that checks if the contact intervention is correctly initialised fail.

```r
close_schools <- intervention(
  name       = "close_schools",
  type       = "contacts",
  time_begin = 100L,
  time_end   = 150L,
  reduction  = matrix(c(0.2, 0.0))
)
names(close_schools)
```

--------

Please include a brief description of the problem with a code example:
I assume that this related to the `...` argument in the `new_intervention()` constructor. 
```r
structure(
    list(
      name       = name,
      time_begin = time_begin,
      time_end   = time_end,
      reduction  = reduction,
      ...
    ),
    class = c(class, "intervention")
  )
```

---------

**Comment by Karim-Mane** [comment]
I figure out the issue with this. 

I modified the constructors prototypes to comply with the expectation from {lintr} (argument order: unnamed arguments first before the named arguement). 

I have restored the previous prototype and add in `# nolint: function_integer_linter` on the corresponding lines.

**Comment by pratikunterwegs** [comment]
Thanks for looking into this and solving it @Karim-Mane
