### ISSUE TITLE
PDF documentation rendering fails on r-universe

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/epidemics#139]
https://github.com/r-universe/epiverse-trace/actions/runs/6773487740

Because of unicode characters in:

https://github.com/epiverse-trace/epidemics/blob/55be2f4dd90bb8457cdedf7042464dd8637aad97/R/model_ebola.R#L137

**Comment by pratikunterwegs** [comment]
Closed via PR but I am monitoring [this run](https://github.com/r-universe/epiverse-trace/actions/runs/6942898103) to check that it does indeed work.
