### ISSUE TITLE
Remove Not Published from repo description?

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epidemics#215]
Now that {epidemics} has had two releases on GitHub, is it worth removing the [Not published - under active development] from the About section of the repository? From the [initial discussion that raised this point](https://github.com/orgs/epiverse-trace/discussions/80) it seems that this tag was more for packages that had not been released and are very unstable. It looks that {epidemics} has been relatively stable since having regular releases.

**Comment by pratikunterwegs** [comment]
Thanks for pointing this out - yes, time to remove, will do.
