### ISSUE TITLE
Mismatch between intervention intensity and expectation for given R0?

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/epidemics#250]
I was exploring the [odin model implementation in the howto repo](https://github.com/epiverse-trace/howto/pull/60) more and noticed that interventions seem to have different effect in odin and original epidemics implementation (despite the two outputs matching in the absence of interventions once model was SEIR - [see this branch](https://github.com/epiverse-trace/howto/tree/further-odin-development)). 

If R0=1.5, then reducing contacts across ages by 33% should cause the epidemic to roughly level off (because R = 1.5*(1-0.33) = 1). Or just under 33% given some immunity has already accumulated. This is what happens with the {odin} implementation. However, in the {epidemics} README implementation, the epidemic seems to level off when the contact reduction is around 15%, suggesting that the effect of interventions may be inflated somewhere in the model code. I get the same behaviour if we have no age-variation in mixing (i.e. all entries of un-normalised contact matrix = 1).

**Comment by pratikunterwegs** [comment]
Just popping in to suggest an answer as I still get notified - see #94 and #97 for changes to how contact interventions were implemented, essentially becoming more impactful. PR #97 wasn't reviewed so it might be good to check if it actually makes sense.

A `<rate_intervention>`, or a function passed to `time_dependence`, that works on the transmission rate would apply a simple scaling (hopefully) identical to the one in the odin-based example.

**Comment by adamkucharski** [comment]
Thanks, that makes sense – had wondered if something like that might be happening (given (1-0.15)^2 is similar to 1-0.3). Have now updated that branch implementation, and with intervention vector `c(0.15,0.15,0.15)` get the following with {epidemics}:

![Screenshot 2024-07-17 at 11 41 43](https://github.com/user-attachments/assets/b61ca12e-edbb-4215-8886-67fd44c190e3)

And this aligned output with {odin}:

![Screenshot 2024-07-17 at 11 46 52](https://github.com/user-attachments/assets/cadbb787-93fe-4f89-b7b4-bdafa6f1b3e1)
