### ISSUE TITLE
Implement an infection class

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/epidemics#38]
This issue is to request the implementation of a class that holds the infection parameters, such as the $R_0$ or infectious period. This would tie in well with #20 and could/should link nicely with {epiparameter} outputs.

Since the models that {epidemics} hopes to offer might require a wide variety of infection parameters, this class should be flexible and inherit from a `list`, with only a few invariants - such as the $R_0$ and infectious period, which are the minimum requirements for an SIR model. The class constructor should most likely be:

```r
infection(r0, infectious_period, ...)
```

It may be worth allowing infection parameters to be passed as `epidist` objects, to work towards #20. In the initial implementation, the `epidemic()` function would access only the mean or median of any `infection` class-members stored as `epidists`. Future steps could involve drawing samples from distributions - some thought required on whether this feature should live in {epidemics} or {scenarios}.

Tagging @joshwlambert and @adamkucharski for any suggestions as {epiparameter} devs.

**Comment by joshwlambert** [comment]
@pratikunterwegs sounds like a good idea. I would need to see how this interfaces with the other functions and classes in {epidemics} to give a full review. As you've started development on this and opened a PR, I'll let you create a working version and then I'll happily review the changes through the PR.
