### ISSUE TITLE
Partial matching

### ISSUE THREAD

**Issue by TimTaylor** [epiverse-trace/epidemics#66]
I'm seeing warnings for partial matching being flagged in the code. It does not seem to be causing any issues at the moment but it is probably still worth handling. Is it worth bringing over @Bisaloo's [setup-options.r](https://github.com/epiverse-trace/packagetemplate/commit/419749e480efa1b9dbe29dbe8af421dfae3c4ba8) from the package template?

**Comment by pratikunterwegs** [comment]
Yeesh, okay thanks I see what's going on!
