### ISSUE TITLE
Add a package design vignette

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/epidemics#69]
This issue is to request the addition of a package design document as a vignette. This will serve as a trial and potential template for additional design documents for other packages.

**Comment by avallecam** [comment]
Is there space for some [personas](https://epiverse-trace.github.io/personas/table.html) as target users' profiles? I'd like to test if may be helpful or informative for defining or delimiting some negotiable or non-negotiable package design principles.

**Comment by pratikunterwegs** [comment]
Thanks @avallecam  - we do have a section in the draft template for the use case, which includes a brief description of the target users. We could add a note that package authors could reference some of the personas if they feel they are useful. Ideally though, the documents would be stand-alone, so not requiring much reference externally.
