### ISSUE TITLE
Allow multiple concurrent interventions

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/epidemics#7]
This issue is to request that `epidemics::epi_demic()` should be able to include multiple, stackable interventions. This would allow examining and comparing the effects of particular sequences of interventions (e.g. school closures before wider measures, or vice versa).

A template for fixes to this issue could be found in the implementation of the multiple (concurrent) vaccination regimes, including the implementation of a `c()` method for `vaccination` objects. See #53 and #52 for details.

As an example:

```r
i1 = intervention(...)
i2 = intervention(...)
all_interventions = c(i1, i2)

epidemic(population, infection, intervention = all_interventions)
```

One conceptual question is whether overlapping contact reduction for a particular demographic group should be additive (in terms of percentage points), or multiplicative.

**Comment by bahadzie** [comment]
Given the following code 
```R
npi_1 <- intervention(
  time_begin = 30,
  time_end = 60,
  contact_reduction = matrix(0.15, nrow = 3)
)

print(npi_1)
# <intervention>
# Intervention name: NA
# Time begin:
#      [,1]
# [1,]   30
# Time end:
#      [,1]
# [1,]   60
# Contact reduction:
#      [,1]
# [1,] 0.15
# [2,] 0.15
# [3,] 0.15

# second dose regime
npi_2 <- intervention(
  time_begin = 45,
  time_end = 75,
  contact_reduction = matrix(0.1, nrow = 3)
)

print(npi_2)
# <intervention>
# Intervention name: NA
# Time begin:
#      [,1]
# [1,]   45
# Time end:
#      [,1]
# [1,]   75
# Contact reduction:
#      [,1]
# [1,]  0.1
# [2,]  0.1
# [3,]  0.1

multi_npi <- c(npi_1, npi_2)
print(multi_npi)

# <intervention>
# Intervention name: NA
# Time begin:
#      npi_1 npi_2
# [1,]    30    45
# Time end:
#      npi_1 npi_2
# [1,]    60    75
# Contact reduction:
#      npi_1 npi_2
# [1,]  0.15   0.1
# [2,]  0.15   0.1
# [3,]  0.15   0.1
```

Should `multi_npi` not be combined only where `time_begin` and `time_end` have overlapping days. So using the code above the output should be
Day 30-45: reduuction 0.15
Day 46-60: reduction  0.25  (0.15 + 0.1)
Day 61-75: reduction  0.10 

and the output of `print(multi_npi)` be 

```R
# <intervention>
# Intervention name: NA
# Time begin:
#      npi_1 npi_2 npi_3
# [1,]    30    46    61
# Time end:
#      npi_1 npi_2 npi_3
# [1,]    45    60    75
# Contact reduction:
#      npi_1 npi_2 npi_3
# [1,]  0.15  0.25   0.1
# [2,]  0.15  0.25   0.1
# [3,]  0.15  0.25   0.1
```

**Comment by pratikunterwegs** [comment]
Thanks @TimTaylor - my question was perhaps more on the lines of, if I have two NPIs overlapping, is the overlap considered a distinct intervention of its own? Perhaps this taxonomy hasn't been worked out yet in public health?

Representing the start and end times in a single intervention object makes it really easy to iterate over the rows of the time and contact reduction matrices in the C++ code, I thought - so went for this rather than a list of interventions. The `+` operator idea is interesting, but the result would be the same as `c()` wouldn't it?
